CREATE TABLE TIPOORGANIZACAO (
  IDTIPOORGANIZACAO INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  DESCTIPOORGANIZACAO VARCHAR(150)  NOT NULL    ,
PRIMARY KEY(IDTIPOORGANIZACAO));



CREATE TABLE TIPOEVENTO (
  IDTIPOEVENTO INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  DESCTIPOEVENTO VARCHAR(150)  NOT NULL    ,
PRIMARY KEY(IDTIPOEVENTO));



CREATE TABLE REGIAO (
  IDREGIAO INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  DESCREGIAO VARCHAR(150)  NOT NULL   COMMENT 'EX.: SUDOESTE, NORDESTE, ETC. (ACHEI NECESSÁRIO CRIAR TABELAS DE ESTADOE REGIAO PARA FACILITAR O DESENVOLVIMENTO DOS RELATORIO FILRTADOS QUE O GUSTAVO PEDIU)'   ,
PRIMARY KEY(IDREGIAO));




CREATE TABLE ESTADO (
  IDESTADO INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  IDREGIAO INTEGER UNSIGNED  NOT NULL  ,
  DESCESTADO VARCHAR(150)  NOT NULL  ,
  UF VARCHAR(150)  NULL    ,
PRIMARY KEY(IDESTADO)  ,
INDEX ESTADO_FKREGIAO(IDREGIAO),
  FOREIGN KEY(IDREGIAO)
    REFERENCES REGIAO(IDREGIAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE CIDADE (
  IDCIDADE INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  IDESTADO INTEGER UNSIGNED  NOT NULL  ,
  DESCCIDADE VARCHAR(150)  NOT NULL    ,
PRIMARY KEY(IDCIDADE)  ,
INDEX CIDADE_FKESTADO(IDESTADO),
  FOREIGN KEY(IDESTADO)
    REFERENCES ESTADO(IDESTADO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE SEDESOFICIAIS (
  IDSEDE INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  IDCIDADE INTEGER UNSIGNED  NOT NULL  ,
  NOME VARCHAR(150)  NOT NULL  ,
  ENDERECO VARCHAR(150)  NOT NULL  ,
  EMAIL VARCHAR(150)  NULL  ,
  TELEFONE VARCHAR(150)  NULL  ,
  DESCRICAO VARCHAR(150)  NULL    ,
PRIMARY KEY(IDSEDE)  ,
INDEX SEDESOFICIAIS_FKIndex1(IDCIDADE),
  FOREIGN KEY(IDCIDADE)
    REFERENCES CIDADE(IDCIDADE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE ORGANIZACAO (
  IDORGANIZACAO INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  IDTIPOORGANIZACAO INTEGER UNSIGNED  NOT NULL  ,
  IDCIDADE INTEGER UNSIGNED  NOT NULL  ,
  NOME INTEGER UNSIGNED  NOT NULL  ,
  ENDERECO INTEGER UNSIGNED  NULL  ,
  EMAIL INTEGER UNSIGNED  NULL  ,
  TELEFONE INTEGER UNSIGNED  NULL    ,
PRIMARY KEY(IDORGANIZACAO)  ,
INDEX ORGANIACAO_FK_CIDADE(IDCIDADE)  ,
INDEX ORGANIACAO_FK_TIPOORGANIZACAO(IDTIPOORGANIZACAO),
  FOREIGN KEY(IDCIDADE)
    REFERENCES CIDADE(IDCIDADE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(IDTIPOORGANIZACAO)
    REFERENCES TIPOORGANIZACAO(IDTIPOORGANIZACAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ORGANIZACAO_IDORGANIZACAO)
    REFERENCES ORGANIZACAO(IDORGANIZACAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE EVENTOS (
  IDEVENTO VARCHAR(150)  NOT NULL  ,
  IDSEDE INTEGER UNSIGNED  NULL  ,
  IDTIPOEVENTO INTEGER UNSIGNED  NOT NULL  ,
  TITULO VARCHAR(150)  NOT NULL  ,
  ENDERECO VARCHAR(150)  NOT NULL  ,
  DATAHORA DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP   ,
PRIMARY KEY(IDEVENTO)  ,
INDEX EVENTOS_FK_TIPOEVENTO(IDTIPOEVENTO)  ,
INDEX EVENTOS_FK_SEDE(IDSEDE),
  FOREIGN KEY(IDTIPOEVENTO)
    REFERENCES TIPOEVENTO(IDTIPOEVENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ORGANIZACAO_IDORGANIZACAO)
    REFERENCES ORGANIZACAO(IDORGANIZACAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(IDSEDE)
    REFERENCES SEDESOFICIAIS(IDSEDE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE USUARIO (
  IDUSUARIO INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  IDCIDADE INTEGER UNSIGNED  NOT NULL  ,
  EMAIL VARCHAR(150)  NOT NULL  ,
  SENHA VARCHAR(150)  NOT NULL  ,
  NOME VARCHAR(150)  NOT NULL  ,
  BOLADMINISTRADOR SMALLINT UNSIGNED  NOT NULL DEFAULT 0   ,
PRIMARY KEY(IDUSUARIO)  ,
INDEX USUARIO_FKCIDADE(IDCIDADE),
  FOREIGN KEY(IDCIDADE)
    REFERENCES CIDADE(IDCIDADE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ORGANIZACAO_IDORGANIZACAO)
    REFERENCES ORGANIZACAO(IDORGANIZACAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



CREATE TABLE LIDERESORGANIZACIONAIS (
  IDUSUARIO INTEGER UNSIGNED  NOT NULL    ,
INDEX LIDERESORGANIZACIONAIS_FK_USUARIO(IDUSUARIO),
  FOREIGN KEY(IDUSUARIO)
    REFERENCES USUARIO(IDUSUARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ORGANIZACAO_IDORGANIZACAO)
    REFERENCES ORGANIZACAO(IDORGANIZACAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION);



